# Tags the SRD bestiary (seeded by db/seeds/monsters.rb) with DMG-style
# environment tags, since the open5e SRD data doesn't carry any. Assignments
# are drawn from D&D lore/DMG encounter tables, not from the source data.
# Safe to re-run: upserts by index, skips anything not in the map.

HABITAT_ASSIGNMENTS = {
  # Aberrations
  'aboleth' => %w[underdark underwater],
  'chuul' => %w[underdark swamp coastal],
  'cloaker' => %w[underdark],
  'gibbering-mouther' => %w[underdark swamp],
  'otyugh' => %w[underdark urban swamp],

  # Chromatic / metallic dragons (all age categories)
  'black-dragon-wyrmling' => %w[swamp], 'young-black-dragon' => %w[swamp], 'adult-black-dragon' => %w[swamp], 'ancient-black-dragon' => %w[swamp],
  'blue-dragon-wyrmling' => %w[desert], 'young-blue-dragon' => %w[desert], 'adult-blue-dragon' => %w[desert], 'ancient-blue-dragon' => %w[desert],
  'brass-dragon-wyrmling' => %w[desert], 'young-brass-dragon' => %w[desert], 'adult-brass-dragon' => %w[desert], 'ancient-brass-dragon' => %w[desert],
  'bronze-dragon-wyrmling' => %w[coastal], 'young-bronze-dragon' => %w[coastal], 'adult-bronze-dragon' => %w[coastal], 'ancient-bronze-dragon' => %w[coastal],
  'copper-dragon-wyrmling' => %w[hill], 'young-copper-dragon' => %w[hill], 'adult-copper-dragon' => %w[hill], 'ancient-copper-dragon' => %w[hill],
  'gold-dragon-wyrmling' => %w[hill], 'young-gold-dragon' => %w[hill], 'adult-gold-dragon' => %w[hill], 'ancient-gold-dragon' => %w[hill],
  'green-dragon-wyrmling' => %w[forest], 'young-green-dragon' => %w[forest], 'adult-green-dragon' => %w[forest], 'ancient-green-dragon' => %w[forest],
  'red-dragon-wyrmling' => %w[mountain], 'young-red-dragon' => %w[mountain], 'adult-red-dragon' => %w[mountain], 'ancient-red-dragon' => %w[mountain],
  'silver-dragon-wyrmling' => %w[mountain arctic], 'young-silver-dragon' => %w[mountain arctic], 'adult-silver-dragon' => %w[mountain arctic], 'ancient-silver-dragon' => %w[mountain arctic],
  'white-dragon-wyrmling' => %w[arctic], 'young-white-dragon' => %w[arctic], 'adult-white-dragon' => %w[arctic], 'ancient-white-dragon' => %w[arctic],
  'dragon-turtle' => %w[underwater coastal],
  'pseudodragon' => %w[forest],
  'wyvern' => %w[mountain hill],

  # Elementals / planar
  'air-elemental' => %w[planar],
  'earth-elemental' => %w[planar underdark],
  'fire-elemental' => %w[planar],
  'water-elemental' => %w[planar underwater],
  'azer' => %w[planar mountain],
  'djinni' => %w[planar desert],
  'efreeti' => %w[planar desert],
  'dust-mephit' => %w[planar desert],
  'ice-mephit' => %w[planar arctic],
  'magma-mephit' => %w[planar mountain],
  'steam-mephit' => %w[planar swamp],
  'gargoyle' => %w[urban hill mountain],
  'invisible-stalker' => %w[planar],
  'salamander' => %w[planar mountain],
  'xorn' => %w[underdark],
  'magmin' => %w[planar mountain],

  # Fey
  'blink-dog' => %w[forest grassland],
  'dryad' => %w[forest],
  'green-hag' => %w[swamp forest],
  'sea-hag' => %w[coastal swamp],
  'satyr' => %w[forest],
  'sprite' => %w[forest],

  # Fiends (planar natives, some also infiltrate cities)
  'balor' => %w[planar],
  'barbed-devil' => %w[planar],
  'bearded-devil' => %w[planar],
  'bone-devil' => %w[planar],
  'chain-devil' => %w[planar urban],
  'dretch' => %w[planar],
  'erinyes' => %w[planar],
  'glabrezu' => %w[planar],
  'hell-hound' => %w[planar mountain],
  'hezrou' => %w[planar swamp],
  'horned-devil' => %w[planar],
  'ice-devil' => %w[planar arctic],
  'imp' => %w[planar urban],
  'lemure' => %w[planar],
  'marilith' => %w[planar],
  'nalfeshnee' => %w[planar],
  'night-hag' => %w[planar swamp forest],
  'nightmare' => %w[planar],
  'pit-fiend' => %w[planar],
  'quasit' => %w[planar urban],
  'rakshasa' => %w[planar urban],
  'succubus-incubus' => %w[planar urban],
  'vrock' => %w[planar],

  # Giants
  'cloud-giant' => %w[mountain planar],
  'ettin' => %w[hill mountain],
  'fire-giant' => %w[mountain urban],
  'frost-giant' => %w[arctic],
  'hill-giant' => %w[hill],
  'ogre' => %w[hill grassland swamp],
  'oni' => %w[hill mountain urban],
  'stone-giant' => %w[mountain underdark],
  'storm-giant' => %w[coastal mountain],
  'troll' => %w[swamp forest hill],

  # Undead
  'ghast' => %w[urban underdark],
  'ghost' => %w[urban underdark],
  'ghoul' => %w[urban underdark],
  'lich' => %w[urban underdark],
  'mummy' => %w[desert],
  'mummy-lord' => %w[desert],
  'shadow' => %w[underdark urban],
  'skeleton' => %w[underdark urban],
  'specter' => %w[underdark urban],
  'vampire-spawn' => %w[urban],
  'vampire-bat' => %w[urban],
  'vampire-mist' => %w[urban],
  'vampire-vampire' => %w[urban],
  'wight' => %w[underdark urban],
  'will-o-wisp' => %w[swamp],
  'wraith' => %w[underdark urban],
  'zombie' => %w[urban underdark],
  'ogre-zombie' => %w[urban underdark],
  'minotaur-skeleton' => %w[underdark],
  'warhorse-skeleton' => %w[urban underdark],

  # Monstrosities
  'ankheg' => %w[grassland forest],
  'basilisk' => %w[underdark hill],
  'behir' => %w[underdark mountain],
  'bulette' => %w[hill grassland underdark],
  'centaur' => %w[forest grassland],
  'chimera' => %w[mountain],
  'cockatrice' => %w[forest swamp],
  'darkmantle' => %w[underdark],
  'death-dog' => %w[desert],
  'doppelganger' => %w[urban],
  'drider' => %w[underdark],
  'ettercap' => %w[forest],
  'gorgon' => %w[grassland hill],
  'griffon' => %w[mountain hill],
  'grick' => %w[underdark],
  'guardian-naga' => %w[urban forest],
  'spirit-naga' => %w[swamp forest],
  'harpy' => %w[coastal mountain swamp],
  'hippogriff' => %w[mountain hill grassland],
  'hydra' => %w[swamp coastal],
  'kraken' => %w[underwater],
  'lamia' => %w[desert],
  'manticore' => %w[mountain hill],
  'medusa' => %w[underdark hill],
  'merrow' => %w[underwater coastal],
  'mimic' => %w[underdark urban],
  'minotaur' => %w[underdark],
  'owlbear' => %w[forest],
  'phase-spider' => %w[underdark forest],
  'purple-worm' => %w[underdark desert],
  'remorhaz' => %w[arctic],
  'roc' => %w[mountain],
  'roper' => %w[underdark],
  'rust-monster' => %w[underdark hill],
  'winter-wolf' => %w[arctic],
  'worg' => %w[forest mountain grassland],
  'androsphinx' => %w[desert],
  'gynosphinx' => %w[desert],

  # Constructs
  'animated-armor' => %w[urban],
  'flying-sword' => %w[urban],
  'rug-of-smothering' => %w[urban],
  'homunculus' => %w[urban],
  'clay-golem' => %w[urban underdark],
  'flesh-golem' => %w[urban underdark],
  'iron-golem' => %w[urban underdark],
  'stone-golem' => %w[urban underdark],
  'shield-guardian' => %w[urban],

  # Humanoids
  'acolyte' => %w[urban],
  'archmage' => %w[urban],
  'assassin' => %w[urban],
  'bandit' => %w[urban grassland hill],
  'bandit-captain' => %w[urban grassland hill],
  'berserker' => %w[hill mountain forest],
  'commoner' => %w[urban],
  'cult-fanatic' => %w[urban],
  'cultist' => %w[urban],
  'druid' => %w[forest],
  'gladiator' => %w[urban],
  'guard' => %w[urban],
  'half-red-dragon-veteran' => %w[urban mountain],
  'knight' => %w[urban],
  'mage' => %w[urban],
  'noble' => %w[urban],
  'priest' => %w[urban],
  'scout' => %w[forest grassland hill],
  'spy' => %w[urban],
  'thug' => %w[urban],
  'tribal-warrior' => %w[forest grassland],
  'veteran' => %w[urban],
  'drow' => %w[underdark],
  'duergar' => %w[underdark],
  'deep-gnome-svirfneblin' => %w[underdark],
  'grimlock' => %w[underdark],
  'gnoll' => %w[grassland desert],
  'goblin' => %w[forest hill underdark],
  'hobgoblin' => %w[forest hill underdark],
  'kobold' => %w[underdark hill],
  'orc' => %w[hill mountain grassland],
  'lizardfolk' => %w[swamp],
  'merfolk' => %w[underwater coastal],
  'sahuagin' => %w[underwater coastal],
  'bugbear' => %w[forest underdark],
  'werebear-bear' => %w[forest], 'werebear-human' => %w[forest], 'werebear-hybrid' => %w[forest],
  'wereboar-boar' => %w[forest], 'wereboar-human' => %w[forest], 'wereboar-hybrid' => %w[forest],
  'wererat-human' => %w[urban underdark], 'wererat-hybrid' => %w[urban underdark], 'wererat-rat' => %w[urban underdark],
  'weretiger-human' => %w[forest grassland], 'weretiger-hybrid' => %w[forest grassland], 'weretiger-tiger' => %w[forest grassland],
  'werewolf-human' => %w[forest], 'werewolf-hybrid' => %w[forest], 'werewolf-wolf' => %w[forest],

  # Plants / oozes / fungi
  'awakened-shrub' => %w[forest],
  'awakened-tree' => %w[forest],
  'shambling-mound' => %w[swamp forest],
  'treant' => %w[forest],
  'violet-fungus' => %w[underdark swamp],
  'shrieker' => %w[underdark swamp],
  'black-pudding' => %w[underdark],
  'gelatinous-cube' => %w[underdark],
  'gray-ooze' => %w[underdark],
  'ochre-jelly' => %w[underdark],

  # Beasts
  'ape' => %w[forest], 'giant-ape' => %w[forest],
  'axe-beak' => %w[grassland],
  'baboon' => %w[forest grassland],
  'badger' => %w[forest grassland hill], 'giant-badger' => %w[forest grassland hill],
  'bat' => %w[underdark forest], 'giant-bat' => %w[underdark forest],
  'black-bear' => %w[forest mountain hill],
  'brown-bear' => %w[forest mountain hill],
  'polar-bear' => %w[arctic],
  'boar' => %w[forest], 'giant-boar' => %w[forest],
  'camel' => %w[desert],
  'cat' => %w[urban],
  'constrictor-snake' => %w[swamp forest], 'giant-constrictor-snake' => %w[swamp forest],
  'crab' => %w[coastal underwater], 'giant-crab' => %w[coastal underwater],
  'crocodile' => %w[swamp coastal], 'giant-crocodile' => %w[swamp coastal],
  'deer' => %w[forest grassland],
  'dire-wolf' => %w[forest grassland arctic],
  'draft-horse' => %w[urban grassland], 'riding-horse' => %w[urban grassland], 'warhorse' => %w[urban grassland],
  'pony' => %w[urban grassland], 'mule' => %w[urban grassland],
  'eagle' => %w[mountain], 'giant-eagle' => %w[mountain],
  'elephant' => %w[grassland],
  'elk' => %w[forest grassland], 'giant-elk' => %w[forest grassland],
  'flying-snake' => %w[forest],
  'frog' => %w[swamp], 'giant-frog' => %w[swamp], 'giant-toad' => %w[swamp],
  'giant-centipede' => %w[underdark forest],
  'giant-fire-beetle' => %w[underdark],
  'giant-goat' => %w[mountain hill],
  'hyena' => %w[grassland desert], 'giant-hyena' => %w[grassland desert],
  'giant-lizard' => %w[underdark desert],
  'giant-octopus' => %w[underwater coastal], 'octopus' => %w[underwater coastal],
  'giant-owl' => %w[forest],
  'giant-poisonous-snake' => %w[forest swamp desert], 'poisonous-snake' => %w[forest swamp desert],
  'giant-rat' => %w[urban underdark], 'giant-rat-diseased' => %w[urban underdark], 'rat' => %w[urban underdark],
  'giant-scorpion' => %w[desert], 'scorpion' => %w[desert],
  'giant-sea-horse' => %w[underwater], 'sea-horse' => %w[underwater],
  'giant-shark' => %w[underwater coastal], 'hunter-shark' => %w[underwater coastal], 'reef-shark' => %w[underwater coastal],
  'giant-spider' => %w[forest underdark], 'spider' => %w[forest underdark], 'giant-wolf-spider' => %w[forest underdark],
  'giant-vulture' => %w[desert grassland mountain], 'vulture' => %w[desert grassland mountain],
  'giant-wasp' => %w[forest grassland],
  'giant-weasel' => %w[forest grassland], 'weasel' => %w[forest grassland],
  'goat' => %w[mountain hill],
  'hawk' => %w[mountain grassland],
  'jackal' => %w[desert grassland],
  'killer-whale' => %w[underwater coastal],
  'lion' => %w[grassland],
  'lizard' => %w[desert underdark],
  'mammoth' => %w[arctic grassland],
  'mastiff' => %w[urban],
  'owl' => %w[forest],
  'panther' => %w[forest],
  'plesiosaurus' => %w[underwater],
  'quipper' => %w[underwater],
  'raven' => %w[forest urban],
  'rhinoceros' => %w[grassland],
  'saber-toothed-tiger' => %w[arctic forest grassland],
  'tiger' => %w[forest grassland],
  'blood-hawk' => %w[grassland hill],
  'stirge' => %w[swamp underdark forest],
  'triceratops' => %w[forest grassland],
  'tyrannosaurus-rex' => %w[forest grassland],
  'wolf' => %w[forest grassland hill],

  # Swarms
  'swarm-of-bats' => %w[underdark forest],
  'swarm-of-beetles' => %w[underdark forest],
  'swarm-of-centipedes' => %w[underdark],
  'swarm-of-insects' => %w[forest swamp],
  'swarm-of-poisonous-snakes' => %w[forest swamp desert],
  'swarm-of-quippers' => %w[underwater],
  'swarm-of-rats' => %w[urban underdark],
  'swarm-of-ravens' => %w[forest urban],
  'swarm-of-spiders' => %w[forest underdark],
  'swarm-of-wasps' => %w[forest grassland],

  # Celestials
  'couatl' => %w[planar forest],
  'deva' => %w[planar urban],
  'pegasus' => %w[grassland forest],
  'planetar' => %w[planar],
  'solar' => %w[planar],
  'unicorn' => %w[forest],
}.freeze

HABITAT_ASSIGNMENTS.each do |index, habitats|
  monster = Monster.find_by(index: index)
  next unless monster

  monster.update!(habitats: habitats)
end

tagged = HABITAT_ASSIGNMENTS.keys.count
puts "Tagged #{tagged} of #{Monster.count} monsters with habitats."
